application: pacaylus
version: 1
runtime: python
api_version: 1

handlers:

- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js
  
- url: /static/img
  static_dir: static/img


- url: /.*
  script: server.py
